'use strict';

let tipConfiguration = null;
let micropayConfigurations = null;
let automaticConfiguration = null;

function initializeExtension() {

    chrome.storage.onChanged.addListener(function(changes, namespace) {
        for (const [key, { oldValue, newValue }] of Object.entries(changes)) {
            if (key == 'privateKey') {
                // Send the public identifier whenever the private key changes.
                sendPublicIdentifierToPage();
            } else if (key.startsWith('authorizedAutomaticAmount_')) {
                // Send any authorized automatic amounts when they change.
                const identifier = key.substring('authorizedAutomaticAmount_'.length);
                sendAuthorizedAutomaticAmountToPage(identifier, newValue);
            }
        }
    });

    // Send an initial update of the public identifier and authorized automatic amounts.
    sendPublicIdentifierToPage();
    sendAuthorizedAutomaticAmountsToPage();

    // Add a listener for automatic transactions generated by the page.
    document.addEventListener('nyzo-transaction-generated', function(event) {

        // If the amount is not defined, set it to μ1.
        var micropayConfiguration = event.detail;
        if (isUndefined(micropayConfiguration.amountMicronyzos)) {
            micropayConfiguration = {
                clientUrl: micropayConfiguration.clientUrl,
                receiverId: micropayConfiguration.receiverId,
                tag: micropayConfiguration.tag,
                amountMicronyzos: 1
            };
        }

        sendTransaction(micropayConfiguration);
    });

    // Add a listener for changes to the page's Micropay configuration.
    document.addEventListener('nyzo-configuration-changed', function() {
        loadConfigurationFromPage();
    });

    // Perform an initial loading of the configuration from the page.
    loadConfigurationFromPage();

    chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
        if (request.action === 'getNyzoParameters') {
            sendResponse({tipConfiguration: tipConfiguration, micropayConfigurations: micropayConfigurations,
                automaticConfiguration: automaticConfiguration});
        } else if (request.action === 'micropayTransactionAvailable') {
            const uniqueReferenceKey = request.uniqueReferenceKey;
            const tag = request.tag;

            chrome.storage.local.get([uniqueReferenceKey, 'privateKey'], function(extensionConfiguration) {
                const privateKey = decode(extensionConfiguration.privateKey).getSeed();

                const transaction = extensionConfiguration[uniqueReferenceKey];
                const supplementalTransaction = createSupplementalTransaction(decode(transaction), privateKey);
                const detailObject = {transaction: transaction,
                    supplementalTransaction: nyzoStringFromTransaction(supplementalTransaction.getBytes(true)),
                    tag: tag};
                const event = new CustomEvent('micropayTransactionAvailable', { detail: detailObject });
                document.dispatchEvent(event);
            });
        }
    });
}

function loadConfigurationFromPage() {

    // Get the tip configuration, if present.
    var tipClientUrl = '';
    var tipReceiverId = '';
    var tipTag = '';
    var tipButtons = document.getElementsByClassName('nyzo-tip-button');
    for (var i = 0; i < tipButtons.length; i++) {
        var button = tipButtons[i];

        // Modify the classes to show that the extension was installed.
        button.classList.add('nyzo-extension-installed');
        button.classList.remove('nyzo-extension-not-installed');

        // If valid, store the client URL, receiver ID, and tag.
        tipClientUrl = button.dataset.clientUrl;
        tipReceiverId = button.dataset.receiverId;
        tipTag = cleanTag(button.dataset.tag);
    }
    tipConfiguration = new MicropayConfiguration(tipClientUrl, tipReceiverId, tipTag, '', 0);

    // Get Micropay configurations, if present.
    micropayConfigurations = [];
    var micropayButtons = document.getElementsByClassName('nyzo-micropay-button');
    for (var i = 0; i < micropayButtons.length; i++) {
        var button = micropayButtons[i];

        // Modify the classes to show that the extension was installed.
        button.classList.add('nyzo-extension-installed');
        button.classList.remove('nyzo-extension-not-installed');

        // If valid, store the client URL, receiver ID, and tag.
        const clientUrl = button.dataset.clientUrl;
        const receiverId = button.dataset.receiverId;
        const tag = cleanTag(button.dataset.tag);
        const displayName = cleanDisplayName(button.dataset.displayName);
        const amountMicronyzos = getAmountMicronyzos(button.dataset.amount);
        const configuration = new MicropayConfiguration(clientUrl, receiverId, tag, displayName, amountMicronyzos);
        if (isValidConfigurationForMicropay(configuration)) {
            micropayConfigurations.push(configuration);
        }
    }

    // Get the automatic authorization configuration, if present.
    let automaticReceiverId = '';
    let automaticMinimumAmount = 0.0;
    let automaticRecommendedAmount = 0.0;
    let automaticDisplayName = '';
    let automaticConfigurationElements = document.getElementsByClassName('nyzo-automatic-authorization');
    for (let i = 0; i < automaticConfigurationElements.length; i++) {
            let element = automaticConfigurationElements[i];

            // Store the parameters.
            automaticReceiverId = element.dataset.receiverId;
            automaticMinimumAmount = element.dataset.minimumAmount;
            automaticRecommendedAmount = element.dataset.recommendedAmount;
            automaticDisplayName = element.dataset.displayName;
        }
    automaticConfiguration = { receiverId: automaticReceiverId, minimumAmount: automaticMinimumAmount,
        recommendedAmount: automaticRecommendedAmount, displayName: automaticDisplayName};
}

function sendTransaction(micropayConfiguration) {

    const authorizationKey = 'authorizedAutomaticAmount_' + micropayConfiguration.receiverId;
    const keys = ['privateKey', 'maximumAutomaticAmount', authorizationKey];
    chrome.storage.local.get(keys, function(extensionConfiguration) {

        // Only continue if extension and micropay configuration parameters are correct. Also, ensure that the amount is
        // less than the maximum allowed for automatic transactions.
        const maximumAutomaticAmountMicronyzos = Math.min(extensionConfiguration.maximumAutomaticAmount *
            micronyzosPerNyzo, extensionConfiguration[authorizationKey]);
        if (isValidPrivateKey(extensionConfiguration.privateKey) &&
            isValidMaximumAutomaticAmount(extensionConfiguration.maximumAutomaticAmount) &&
            micropayConfiguration.amountMicronyzos <= maximumAutomaticAmountMicronyzos &&
            isValidClientUrl(micropayConfiguration.clientUrl) &&
            isValidPublicIdentifier(micropayConfiguration.receiverId) &&
            micropayConfiguration.tag != null && micropayConfiguration.tag.length > 0) {

            // Deduct the transaction amount from the authorization.
            const adjustedAuthorization = extensionConfiguration[authorizationKey] -
                micropayConfiguration.amountMicronyzos;
            chrome.storage.local.set({[authorizationKey]: adjustedAuthorization});

            // Gather the information and submit the transaction.
            const timestamp = Date.now() + 10000;
            const privateKey = decode(extensionConfiguration.privateKey).getSeed();
            const receiverIdentifierArray = decode(micropayConfiguration.receiverId).getIdentifier();
            const amountMicronyzos = micropayConfiguration.amountMicronyzos;
            const senderData = stringAsUint8Array(micropayConfiguration.tag);
            const clientUrl = micropayConfiguration.clientUrl;
            submitTransaction(timestamp, privateKey, receiverIdentifierArray, amountMicronyzos, senderData, clientUrl,
                function(success, messages, warnings, errors, transaction) {

                    // Let the page know whether the transaction was accepted.
                    if (success) {
                        // Store the transaction in local storage.
                        const uniqueReferenceKey = uniqueReferenceKeyForMicropayConfiguration(micropayConfiguration);
                        const objectToStore = new Object();
                        objectToStore[uniqueReferenceKey] = transaction;
                        chrome.storage.local.set(objectToStore);

                        // Send an 'accepted' notification.
                        const detailObject = {
                            tag: micropayConfiguration.tag,
                            clientUrl: micropayConfiguration.clientUrl,
                            amountMicronyzos: micropayConfiguration.amountMicronyzos,
                            receiverId: micropayConfiguration.receiverId,
                            transaction: transaction
                        };
                        const event = new CustomEvent('nyzo-transaction-accepted', { detail: detailObject });
                        document.dispatchEvent(event);
                    } else {
                        // Send a 'failed' notification.
                        const event = new CustomEvent('nyzo-transaction-failed', { detail: micropayConfiguration });
                        document.dispatchEvent(event);
                    }
                }
            );
        } else {
            // Send a 'failed' notification.
            const event = new CustomEvent('nyzo-transaction-failed', { detail: micropayConfiguration });
            document.dispatchEvent(event);
        }
    });
}

function sendPublicIdentifierToPage() {
    chrome.storage.local.get(['privateKey'], function(extensionConfiguration) {
        let publicIdentifier = publicIdentifierForPrivateKey(extensionConfiguration.privateKey);
        const event = new CustomEvent('nyzo-public-identifier-configured', { detail: publicIdentifier });
        document.dispatchEvent(event);
    });
}

function sendAuthorizedAutomaticAmountsToPage() {
    chrome.storage.local.get(null, function(extensionConfiguration) {
        for (const [key, value] of Object.entries(extensionConfiguration)) {
            if (key.startsWith('authorizedAutomaticAmount_')) {
                const identifier = key.substring('authorizedAutomaticAmount_'.length);
                sendAuthorizedAutomaticAmountToPage(identifier, value);
            }
        }
    });
}

function sendAuthorizedAutomaticAmountToPage(identifier, amount) {
    if (isValidPublicIdentifier(identifier)) {
        const detailObject = {
            identifier: identifier,
            amount: amount
        };
        const event = new CustomEvent('nyzo-automatic-authorization-available', { detail: detailObject });
        document.dispatchEvent(event);
    }
}

initializeExtension();
